name: "OCI runner"
permissions: write-all
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEBIAN_FRONTEND: "noninteractive"
  TZ: "Asia/Jakarta"
  NTFY: ${{ secrets.NTFY }}
  OCI_CLI_RC_FILE: "/root/.oci/config"
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: oci-runner
      - uses: actions/checkout@v4
        with:
          repository: musahi-0128/oci-docker
          token: ${{ secrets.GH_PAT }}
          path: oci-docker
      - shell: bash
        run: |
          sudo apt update --fix-missing
          sudo apt remove firefox --purge
          sudo su - runner -c 'docker system prune -a -f'
          sudo rm -rf /usr/local/lib/android
          sudo apt upgrade -y
          curl -sL -o /tmp/oci-install.sh https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          bash /tmp/oci-install.sh --accept-all-defaults
          rm /tmp/oci-install.sh
          sudo apt autoremove --purge
          sudo apt clean
          sudo curl -sL -o /usr/local/bin/ttyd $(curl -s 'https://api.github.com/repos/tsl0922/ttyd/releases/latest' | jq -r '.assets[] | select(.name|contains("x86_64")).browser_download_url')
          sudo chmod a+x /usr/local/bin/ttyd
          mkdir -p /home/runner/.oci /home/runner/.ssh
          sed -i 's#\/root\/.ssh#\/home\/runner\/.ssh#g' oci-docker/oci/config
          sed -i 's#\/root#\/home\/runner#g' oci-docker/oci/oci-launch-instance.sh
          cp oci-docker/oci/* /home/runner/.oci/
          cp oci-docker/ssh/* /home/runner/.ssh/
          chmod 600 /home/runner/.ssh/*
          /home/runner/bin/oci setup repair-file-permissions --file /home/runner/.oci/config
          /home/runner/bin/oci setup repair-file-permissions --file /home/runner/.ssh/id_rsa
          sed -i 's#ubuntu#runner#g' oci-docker/systemd/ttyd.service
          sed -i 's#ubuntu#runner#g' oci-docker/systemd/srv.us.service
          sudo cp oci-docker/systemd/* /etc/systemd/system/
          echo "GH_TOKEN=$GH_TOKEN" > /home/runner/.config/systemd.env
          sudo systemctl enable --now ttyd.service srv.us.service
          while [ ! $(journalctl -u srv.us --no-pager -o cat | grep 'https:') == 1 ]; do sleep 3; done
          curl -s -d "$(echo OCI Runner; echo Connection information:; journalctl -u srv.us --no-pager -o cat | grep 'https:')" ntfy.sh/$NTFY > /dev/null 2>&1
          for a in {1..60}
            do
              [ -f /tmp/poweroff ] && echo "Stop signal has been received. Stopping instance." && exit
              [ -f /tmp/success ] && echo "Congratulation! you have succesfully get an instance running." && exit || (echo "Attempting, $a of 60" && bash /home/runner/.oci/oci-launch-instance.sh >> /tmp/oci-launch-instance.out 2>&1)
          done
          [ ! -f /tmp/poweroff -o ! -f /tmp/success ] && gh workflow run launch_instance.yml || exit
