name: "OCI runner with docker image"
permissions: write-all
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NTFY: ${{ secrets.NTFY }}
  OCI_CLI_RC_FILE: "/root/.oci/config"
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/musahi-0128/oci-docker:main
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          mkdir -p /home/ubuntu/.config/
          echo "GH_TOKEN=$GH_TOKEN" > /home/ubuntu/.config/systemd.env
          sudo systemctl enable --now ttyd.service srv.us.service
          while [ ! $(sudo journalctl -u srv.us | grep 'https:') == 1 ]; do sleep 3; done
          curl -s -d "$(echo OCI Runner; echo Connection information:; sudo journalctl -u srv.us | grep 'https:')" ntfy.sh/$NTFY > /dev/null 2>&1
          for a in {1..60}
            do
              [ -f /tmp/poweroff ] && echo "Stop signal has been received. Stopping instance." && exit
              [ -f /tmp/success ] && echo "Congratulation! you have succesfully get an instance running." && exit || (echo "Attempting, $a of 60" && sudo /bin/bash /root/.oci/oci-launch-instance.sh >> /tmp/oci-launch-instance.out 2>&1)
          done
          [ ! -f /tmp/poweroff -o ! -f /tmp/success ] && gh workflow run launch_instance.yml || exit
