name: "OCI runner"
permissions: write-all
on:
  workflow_dispatch:
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NTFY: ${{ secrets.NTFY }}
    OCI_CLI_RC_FILE: "/root/.oci/config"
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/musahi-0128/oci-docker:main
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Launch instance
        shell: bash
        run: |
          mkdir -p /home/ubuntu/.config/
          echo "GH_TOKEN=$GH_TOKEN" > /home/ubuntu/.config/systemd.env
          sudo systemctl enable --now ttyd.service srv.us.service
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ServerAliveInterval=5 -T srv.us -R 1:127.0.0.1:7681 2> /dev/null > /tmp/srv.us.addr &
          sleep 1 && kill %1
          curl -s -d "$(echo OCI Runner; echo Connection information:; cat /tmp/srv.us.addr)" ntfy.sh/$NTFY > /dev/null 2>&1
          for a in {1..60}
            do
              [ -f /tmp/poweroff ] && echo "Stop signal has been received. Stopping instance." && exit
              [ -f /tmp/success ] && echo "Congratulation! you have succesfully get an instance running." && exit || (echo "Attempting, $a of 60" && sudo /bin/bash /root/.oci/oci-launch-instance.sh >> /tmp/oci-launch-instance.out 2>&1)
          done
          [[ ! -f /tmp/poweroff || ! -f /tmp/success ]] && gh workflow run launch_instance.yml || exit
